Add initial version of http transport
Financial-Times/gourmet pull request #5
Opened 2021-07-28 13:40 UTC by gotha

2021-07-28 17:10 UTC, atanasdinov requested changes
Up for discussion:

- The decoder functions are looking good however shouldn't we have one constructing a "hybrid" request from both query params and body?
- The `apperror` package is too complex with all the wrapping and unwrapping functions. My suggestion is simplifying those to `New(errType ErrorType, message string, args... interface{})` and `Wrap(errType ErrorType, err error, message string, args... interface{})`. Then we have the option of using formatted messages without additional functions and possibly removing the `github.com/pkg/errors` package altogether. To my understanding `AppError` will be constructed as a final error from a given action e.g. concluding a HTTP response. We wouldn't be flooding our services with `AppError` wrapping on each possible error.

2021-07-28 17:10 UTC, atanasdinov commented on transport/http/lifecycle.go
> +func NewServerLifecycle(srv *Server) *ServerLifecycle {
Don't we want to return the `Lifecycle` interface from the `app` package?

2021-07-29 13:50 UTC, gotha commented on transport/http/server.go
> +func statusCodeFromError(err error) int {
maybe this should be an option that can be overridden

2021-07-31 22:39 UTC, gotha commented on transport/http/decoder.go
> +		body, err := ioutil.ReadAll(httpReq.Body)
I am receiving the request, not sending it. There is no need to close the body. 
```
        // Body is the request's body.
	//
	// For client requests, a nil body means the request has no
	// body, such as a GET request. The HTTP Client's Transport
	// is responsible for calling the Close method.
	//
	// For server requests, the Request Body is always non-nil
	// but will return EOF immediately when no body is present.
	// The Server will close the request body. The ServeHTTP
	// Handler does not need to.
	//
	// Body must allow Read to be called concurrently with Close.
	// In particular, calling Close should unblock a Read waiting
	// for input.
	Body io.ReadCloser
```

2021-08-03 15:36 UTC, atanasdinov approved these changes

2021-08-04 15:35 UTC, merged